version: '3.5'

services:

  schelly-sample:
    build: .
    ports:
      - 7070:7070
    environment:
      - LOG_LEVEL=debug
      - PRE_BACKUP_COMMAND=/pre-backup.sh
      - POST_BACKUP_COMMAND=/post-backup.sh
      - PRE_POST_TIMEOUT_SECONDS=10
